CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_SWAP_XY=y
CONFIG_PMW3610_ALT_INVERT_X=y
CONFIG_PMW3610_ALT_INVERT_Y=y
