on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

  debug:
    - name: dump
      run: |
        grep -n "chosen" -A20 build/zephyr/zephyr.dts || true
        grep -n "kscan0" -A40 build/zephyr/zephyr.dts || true
        grep -n "five_column_transform" -A40 build/zephyr/zephyr.dts || true
        grep -n "gpio-map" -A80 build/zephyr/zephyr.dts || true
        grep -n "trackball" -A40 build/zephyr/zephyr.dts || true
        echo "next"
        grep -E "CONFIG_ZMK_SPLIT|CONFIG_ZMK_BLE|CONFIG_ZMK_POINTING|CONFIG_INPUT|CONFIG_SPI|CONFIG_PMW|CONFIG_KSCAN|CONFIG_ZMK_STUDIO" build/zephyr/.config || true